# Site settings
title: Zakaria Boualaid
email: zakaria.boualaid@gmail.com
description: "Currently a Full-Stack Developer at Umbreo and would love to share some of my thoughts and ideas through this blog."
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://zakariaboualaid.me" # the base hostname & protocol for your site
fullname: Zakaria Boualaid
twitter_username: zakariaboualaid
github_username: ZakariaBoualaid
facebook_username: zakaria.boulaid
medium_username: '@zakariaboualaid'

assets:
  sources:
    - fonts
# Build settings
markdown: kramdown